M48
; DRILL file {KiCad 8.0.6} date 2024-11-30T03:54:52-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-30T03:54:52-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1358
%
G90
G05
T1
X5.1709Y-2.3287
X5.3984Y-2.3287
T2
X6.9626Y-3.0215
X6.9626Y-3.4715
M30
